services:
  - type: web
    name: ai-support-portal
    runtime: docker
    repo: https://github.com/harshabasava970-bot/-AI-Powered-Customer-Support-Complaint-Management-System
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        value: jdbc:mysql://mysql-3bfe215c-harshabasava970-2b90.b.aivencloud.com:14858/defaultdb?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=30000&socketTimeout=60000
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: PORT
        value: "8080"
    healthCheckPath: /login
    autoDeploy: true
